openapi: 3.0.3
info:
  title: Skoda API Server
  version: 2.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: location
    description: location
  - name: status
    description: status
  - name: vehicle
    description: vehicle
  - name: range
    description: range
  - name: air-conditioning
    description: air conditioning
paths:
  /location/{vin}:
    get:
      tags:
        - location
      operationId: getLocation
      summary: Get location
      parameters:
        - name: vin
          in: path
          description: vehicle vin
          required: true
          schema:
            type: string
            example: QMGAG8BEQSY003476
      responses:
        200:
          description: Request successfully processed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocationWebResponseResource'
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponseResource'
  /status/{vin}:
    get:
      tags:
        - status
      operationId: getStatus
      summary: Get status
      parameters:
        - name: vin
          in: path
          description: vehicle vin
          required: true
          schema:
            type: string
            example: QMGAG8BEQSY003476
      responses:
        200:
          description: Request successfully processed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusWebResponseResource'
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponseResource'
  /vehicle:
    get:
      tags:
        - vehicle
      operationId: findAllVehicles
      summary: Find all vehicles
      responses:
        200:
          description: Request successfully processed
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VehicleWebResponseResource'
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponseResource'
  /range/{vin}:
    get:
      tags:
        - range
      operationId: getRange
      summary: Get range
      parameters:
        - name: vin
          in: path
          description: vehicle vin
          required: true
          schema:
            type: string
            example: QMGAG8BEQSY003476
      responses:
        200:
          description: Request successfully processed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RangeWebResponseResource'
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponseResource'
  /air-conditioning/{vin}:
    get:
      tags:
        - air-conditioning
      operationId: getAirConditioning
      summary: Get air conditioning
      parameters:
        - name: vin
          in: path
          description: vehicle vin
          required: true
          schema:
            type: string
            example: QMGAG8BEQSY003476
      responses:
        200:
          description: Request successfully processed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirConditioningWebResponseResource'
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponseResource'
  /air-conditioning/{vin}/start:
    post:
      tags:
        - air-conditioning
      operationId: startAirConditioning
      summary: Start air conditioning
      parameters:
        - name: vin
          in: path
          description: vehicle vin
          required: true
          schema:
            type: string
            example: QMGAG8BEQSY003476
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AirConditioningWebRequestResource'
      responses:
        202:
          description: Request successfully processed
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponseResource'
  /air-conditioning/{vin}/stop:
    post:
      tags:
        - air-conditioning
      operationId: stopAirConditioning
      summary: Stop air conditioning
      parameters:
        - name: vin
          in: path
          description: vehicle vin
          required: true
          schema:
            type: string
            example: QMGAG8BEQSY003476
      responses:
        202:
          description: Request successfully processed
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponseResource'
components:
  schemas:
    LocationWebResponseResource:
      required:
        - latitude
        - longitude
        - address
      type: object
      properties:
        latitude:
          type: number
          format: double
          description: latitude
          example: 17.292954
        longitude:
          type: number
          format: double
          description: longitude
          example: 2.87205
        address:
          type: string
          example: Rue Red 16, 1000 Brussels, Belgium
    StatusWebResponseResource:
      required:
        - doorsLocked
        - locked
        - doors
        - windows
        - lights
        - reliableLockStatus
        - sunroof
        - trunk
        - bonnet
        - carCapturedTimestamp
      type: object
      properties:
        doorsLocked:
          type: string
        locked:
          type: string
        doors:
          type: string
        windows:
          type: string
        lights:
          type: string
        reliableLockStatus:
          type: string
        sunroof:
          type: string
        trunk:
          type: string
        bonnet:
          type: string
        carCapturedTimestamp:
          type: string
    VehicleWebResponseResource:
      required:
        - vin
        - name
        - licensePlate
        - state
        - devicePlatform
        - systemModelId
        - title
      type: object
      properties:
        vin:
          type: string
          description: vin of the vehicle
          example: QMGAG8BEQSY003476
        name:
          type: string
          description: name of the vehicle
          example: Skoda octavia
        licensePlate:
          type: string
          description: licence plate of the vehicle
          example: 2ABC123
        state:
          type: string
        devicePlatform:
          type: string
        systemModelId:
          type: string
        title:
          type: string
    RangeWebResponseResource:
      required:
        - carType
        - totalRangeInKm
        - engineType
        - currentSoCInPercent
        - remainingRangeInKm
        - carCapturedTimestamp
      properties:
        carType:
          type: string
        totalRangeInKm:
          type: integer
          format: int32
        engineType:
          type: string
        currentSoCInPercent:
          type: integer
          format: int32
        remainingRangeInKm:
          type: integer
          format: int32
        carCapturedTimestamp:
          type: string
    AirConditioningWebResponseResource:
      required:
        - state
        - temperature
        - temperatureUnit
        - carCapturedTimestamp
      properties:
        state:
          type: string
        temperature:
          type: number
          format: double
        temperatureUnit:
          type: string
        carCapturedTimestamp:
          type: string
    AirConditioningWebRequestResource:
      required:
        - heaterSource
        - temperature
        - temperatureUnit
      properties:
        heaterSource:
          type: string
          description: heater source
          example: ELECTRIC
        temperature:
          type: number
          format: double
          description: target temperature in degree Celsius
          example: 21.5
        temperatureUnit:
          type: string
          description: target temperature unit
          example: CELSIUS
    ProblemDetailResponseResource:
      required:
        - title
        - status
        - detail
        - instance
      properties:
        title:
          type: string
          description: A short, human-readable summary of the problem type
          example: Invalid vin
        status:
          type: integer
          description: The HTTP status code generated by the origin server for this occurrence of the problem
          example: 400
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem
          example: Invalid vin, please check your vin
        instance:
          type: string
          description: A URI reference that identifies the specific occurrence of the problem
          example: /cooling
